import json

def generate_notebook():
    notebook = {
        "cells": [
            # ── Title ──────────────────────────────────────
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "# 🤖 Module 3: Tool Calling & Function Calling\n",
                    "\n",
                    "**Goal:** Understand and build the tool-calling loop that transforms an LLM into an agent.\n",
                    "\n",
                    "We go step by step:\n",
                    "1. Simulate tool calling manually (no API needed)\n",
                    "2. Build a proper Tool Registry\n",
                    "3. Build the full Agent Execution Loop\n",
                    "4. Test with multiple tools + error handling\n",
                    "5. Use a real LLM API (optional — Groq free tier)\n",
                    "\n",
                    "> **No GPU needed.** All cells run on free Colab CPU."
                ]
            },

            # ── Step 1: Concept ────────────────────────────
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "---\n",
                    "## Step 1: The Core Idea — LLM Outputs a Request, Not an Answer\n",
                    "\n",
                    "Instead of answering directly, the LLM outputs a structured JSON telling us **which tool to call** and **with what arguments**.\n",
                    "\n",
                    "Your application then:\n",
                    "1. Reads the tool call\n",
                    "2. Runs the real Python function\n",
                    "3. Gives the result back to the LLM\n",
                    "4. The LLM uses the result to write the final answer\n"
                ]
            },

            # ── Step 2: Manual Simulation ──────────────────
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": ["---\n## Step 2: Manually Simulate a Tool Call (No API)\n\nLet's manually act as the LLM to understand the full flow."]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "import json\n",
                    "\n",
                    "# ──────────────────────────────────────────────────\n",
                    "# STEP A: Define our tools as Python functions\n",
                    "# ──────────────────────────────────────────────────\n",
                    "\n",
                    "def get_weather(city: str) -> str:\n",
                    "    \"\"\"Simulated weather API\"\"\"\n",
                    "    weather_db = {\n",
                    "        \"dhaka\":  \"32°C, Humid, Partly Cloudy\",\n",
                    "        \"london\": \"15°C, Rainy\",\n",
                    "        \"tokyo\":  \"22°C, Clear Sky\",\n",
                    "    }\n",
                    "    result = weather_db.get(city.lower(), \"City not found\")\n",
                    "    return result\n",
                    "\n",
                    "def calculate(a: float, b: float, operation: str) -> str:\n",
                    "    \"\"\"Simulated calculator\"\"\"\n",
                    "    ops = {\n",
                    "        \"add\":      a + b,\n",
                    "        \"subtract\": a - b,\n",
                    "        \"multiply\": a * b,\n",
                    "        \"divide\":   a / b if b != 0 else \"Error: division by zero\",\n",
                    "    }\n",
                    "    result = ops.get(operation, \"Unknown operation\")\n",
                    "    return str(result)\n",
                    "\n",
                    "def search_web(query: str) -> str:\n",
                    "    \"\"\"Simulated web search\"\"\"\n",
                    "    results = {\n",
                    "        \"python tutorial\": \"Python is a high-level programming language. Official docs: python.org\",\n",
                    "        \"llm agents\":      \"LLM agents use tool calling to interact with the external world.\",\n",
                    "    }\n",
                    "    for key in results:\n",
                    "        if key in query.lower():\n",
                    "            return results[key]\n",
                    "    return f\"No results found for: {query}\"\n",
                    "\n",
                    "print(\"✅ Tools defined!\")\n",
                    "print(\"Test get_weather('Dhaka'):\", get_weather('Dhaka'))\n",
                    "print(\"Test calculate(25, 47, 'multiply'):\", calculate(25, 47, 'multiply'))"
                ]
            },

            # ── Step 3: Tool Schemas ───────────────────────
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": ["---\n## Step 3: Define Tool Schemas (What the LLM Reads)\n\nThe LLM doesn't see our Python code — it only sees **JSON schemas** that describe what each tool does."]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "TOOL_SCHEMAS = [\n",
                    "    {\n",
                    "        \"name\": \"get_weather\",\n",
                    "        \"description\": \"Get current weather conditions for a city. Use when the user asks about weather, temperature, or climate.\",\n",
                    "        \"parameters\": {\n",
                    "            \"type\": \"object\",\n",
                    "            \"properties\": {\n",
                    "                \"city\": {\n",
                    "                    \"type\": \"string\",\n",
                    "                    \"description\": \"City name, e.g. 'Dhaka', 'London'\"\n",
                    "                }\n",
                    "            },\n",
                    "            \"required\": [\"city\"]\n",
                    "        }\n",
                    "    },\n",
                    "    {\n",
                    "        \"name\": \"calculate\",\n",
                    "        \"description\": \"Perform arithmetic calculations. Use when the user asks for math operations.\",\n",
                    "        \"parameters\": {\n",
                    "            \"type\": \"object\",\n",
                    "            \"properties\": {\n",
                    "                \"a\":         {\"type\": \"number\", \"description\": \"First number\"},\n",
                    "                \"b\":         {\"type\": \"number\", \"description\": \"Second number\"},\n",
                    "                \"operation\": {\"type\": \"string\", \"description\": \"One of: add, subtract, multiply, divide\"}\n",
                    "            },\n",
                    "            \"required\": [\"a\", \"b\", \"operation\"]\n",
                    "        }\n",
                    "    },\n",
                    "    {\n",
                    "        \"name\": \"search_web\",\n",
                    "        \"description\": \"Search the web for information. Use when the user asks a factual question you don't know.\",\n",
                    "        \"parameters\": {\n",
                    "            \"type\": \"object\",\n",
                    "            \"properties\": {\n",
                    "                \"query\": {\"type\": \"string\", \"description\": \"Search query string\"}\n",
                    "            },\n",
                    "            \"required\": [\"query\"]\n",
                    "        }\n",
                    "    }\n",
                    "]\n",
                    "\n",
                    "print(\"✅ Tool schemas defined:\")\n",
                    "for t in TOOL_SCHEMAS:\n",
                    "    print(f\"  - {t['name']}: {t['description'][:50]}...\")"
                ]
            },

            # ── Step 4: Tool Registry ──────────────────────
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": ["---\n## Step 4: Tool Registry — Map Names to Functions\n\nThe registry connects the tool name (string from LLM) to the actual Python function."]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# The registry maps tool name → Python function\n",
                    "TOOL_REGISTRY = {\n",
                    "    \"get_weather\": get_weather,\n",
                    "    \"calculate\":   calculate,\n",
                    "    \"search_web\":  search_web,\n",
                    "}\n",
                    "\n",
                    "def execute_tool(tool_name: str, tool_args: dict) -> str:\n",
                    "    \"\"\"\n",
                    "    Execute a tool by name with given arguments.\n",
                    "    Returns result as string, handles errors gracefully.\n",
                    "    \"\"\"\n",
                    "    if tool_name not in TOOL_REGISTRY:\n",
                    "        return f\"Error: Tool '{tool_name}' not found. Available: {list(TOOL_REGISTRY.keys())}\"\n",
                    "    \n",
                    "    try:\n",
                    "        func = TOOL_REGISTRY[tool_name]\n",
                    "        result = func(**tool_args)  # unpack args dict as keyword arguments\n",
                    "        return str(result)\n",
                    "    except Exception as e:\n",
                    "        return f\"Error executing {tool_name}: {str(e)}\"\n",
                    "\n",
                    "# Test the registry\n",
                    "print(\"Test registry dispatch:\")\n",
                    "result = execute_tool(\"get_weather\", {\"city\": \"Dhaka\"})\n",
                    "print(f\"  get_weather(Dhaka) → {result}\")\n",
                    "\n",
                    "result = execute_tool(\"calculate\", {\"a\": 25, \"b\": 47, \"operation\": \"multiply\"})\n",
                    "print(f\"  calculate(25*47) → {result}\")\n",
                    "\n",
                    "# Test error handling\n",
                    "result = execute_tool(\"nonexistent_tool\", {})\n",
                    "print(f\"  nonexistent_tool → {result}\")"
                ]
            },

            # ── Step 5: Simulated LLM ──────────────────────
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "---\n",
                    "## Step 5: Simulated LLM (No API Key Needed)\n",
                    "\n",
                    "We simulate the LLM's decision-making to understand the format exactly.\n",
                    "The LLM returns one of two things:\n",
                    "- A **tool call** (JSON)\n",
                    "- A **final text answer**\n"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "def simulated_llm(messages: list) -> dict:\n",
                    "    \"\"\"\n",
                    "    This simulates what an LLM would return.\n",
                    "    In real usage, this is replaced by an API call.\n",
                    "    \n",
                    "    Returns either:\n",
                    "      {\"type\": \"tool_call\", \"tool\": \"name\", \"args\": {...}}\n",
                    "      {\"type\": \"answer\",    \"content\": \"final text\"}\n",
                    "    \"\"\"\n",
                    "    last_user_msg = \"\"\n",
                    "    last_tool_result = None\n",
                    "    \n",
                    "    for msg in messages:\n",
                    "        if msg[\"role\"] == \"user\":\n",
                    "            last_user_msg = msg[\"content\"]\n",
                    "        if msg[\"role\"] == \"tool\":\n",
                    "            last_tool_result = msg[\"content\"]\n",
                    "    \n",
                    "    # If we have a tool result, generate final answer\n",
                    "    if last_tool_result:\n",
                    "        return {\n",
                    "            \"type\": \"answer\",\n",
                    "            \"content\": f\"Based on the information retrieved: {last_tool_result}. Hope that helps!\"\n",
                    "        }\n",
                    "    \n",
                    "    # Otherwise, decide which tool to call\n",
                    "    msg_lower = last_user_msg.lower()\n",
                    "    \n",
                    "    if \"weather\" in msg_lower:\n",
                    "        # Extract city name (simple heuristic)\n",
                    "        city = \"Dhaka\"  # default\n",
                    "        for word in last_user_msg.split():\n",
                    "            if word[0].isupper() and len(word) > 2:\n",
                    "                city = word\n",
                    "                break\n",
                    "        return {\"type\": \"tool_call\", \"tool\": \"get_weather\", \"args\": {\"city\": city}}\n",
                    "    \n",
                    "    elif any(op in msg_lower for op in [\"multiply\", \"calculate\", \"plus\", \"times\", \"*\"]):\n",
                    "        return {\"type\": \"tool_call\", \"tool\": \"calculate\",\n",
                    "                \"args\": {\"a\": 25, \"b\": 47, \"operation\": \"multiply\"}}\n",
                    "    \n",
                    "    elif \"search\" in msg_lower or \"what is\" in msg_lower:\n",
                    "        return {\"type\": \"tool_call\", \"tool\": \"search_web\",\n",
                    "                \"args\": {\"query\": last_user_msg}}\n",
                    "    \n",
                    "    else:\n",
                    "        return {\"type\": \"answer\", \"content\": f\"I can answer that directly: {last_user_msg}\"}\n",
                    "\n",
                    "print(\"✅ Simulated LLM ready\")"
                ]
            },

            # ── Step 6: Agent Loop ─────────────────────────
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": ["---\n## Step 6: The Agent Execution Loop\n\nThis is the heart of every AI agent — the loop that keeps running until the LLM gives a final answer."]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "def run_agent(user_query: str, max_steps: int = 10) -> str:\n",
                    "    \"\"\"\n",
                    "    Full agent execution loop.\n",
                    "    \n",
                    "    Steps:\n",
                    "    1. Initialize conversation with system prompt + user message\n",
                    "    2. Call LLM\n",
                    "    3. If tool call → execute tool → append result → go to step 2\n",
                    "    4. If final answer → return it\n",
                    "    5. If max_steps reached → return error\n",
                    "    \"\"\"\n",
                    "    print(f\"\\n{'='*55}\")\n",
                    "    print(f\"USER: {user_query}\")\n",
                    "    print(f\"{'='*55}\")\n",
                    "    \n",
                    "    # Initialize conversation\n",
                    "    messages = [\n",
                    "        {\n",
                    "            \"role\": \"system\",\n",
                    "            \"content\": \"You are a helpful assistant with access to weather, calculator, and web search tools.\"\n",
                    "        },\n",
                    "        {\n",
                    "            \"role\": \"user\",\n",
                    "            \"content\": user_query\n",
                    "        }\n",
                    "    ]\n",
                    "    \n",
                    "    for step in range(max_steps):\n",
                    "        print(f\"\\n--- Step {step + 1} ---\")\n",
                    "        \n",
                    "        # Call the LLM (simulated here, real API in Step 7)\n",
                    "        response = simulated_llm(messages)\n",
                    "        \n",
                    "        if response[\"type\"] == \"answer\":\n",
                    "            # ✅ LLM has a final answer — return it\n",
                    "            print(f\"AGENT: {response['content']}\")\n",
                    "            return response[\"content\"]\n",
                    "        \n",
                    "        elif response[\"type\"] == \"tool_call\":\n",
                    "            tool_name = response[\"tool\"]\n",
                    "            tool_args = response[\"args\"]\n",
                    "            \n",
                    "            print(f\"AGENT calls tool: {tool_name}\")\n",
                    "            print(f\"  Arguments: {json.dumps(tool_args)}\")\n",
                    "            \n",
                    "            # Execute the tool\n",
                    "            tool_result = execute_tool(tool_name, tool_args)\n",
                    "            print(f\"  Tool result: {tool_result}\")\n",
                    "            \n",
                    "            # Append tool call and result to conversation history\n",
                    "            messages.append({\n",
                    "                \"role\": \"assistant\",\n",
                    "                \"content\": None,\n",
                    "                \"tool_call\": {\"name\": tool_name, \"args\": tool_args}\n",
                    "            })\n",
                    "            messages.append({\n",
                    "                \"role\": \"tool\",\n",
                    "                \"tool_name\": tool_name,\n",
                    "                \"content\": tool_result\n",
                    "            })\n",
                    "    \n",
                    "    return \"Error: Agent reached maximum steps without a final answer.\"\n",
                    "\n",
                    "print(\"✅ Agent loop ready\")"
                ]
            },

            # ── Step 7: Test ───────────────────────────────
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": ["---\n## Step 7: Test the Agent with Different Queries"]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# Test 1: Weather query\n",
                    "answer = run_agent(\"What is the weather in London today?\")\n",
                    "\n",
                    "# Test 2: Math query\n",
                    "answer = run_agent(\"Can you multiply 25 times 47?\")\n",
                    "\n",
                    "# Test 3: Search query\n",
                    "answer = run_agent(\"Search for information about LLM agents\")"
                ]
            },

            # ── Step 8: Message Anatomy ────────────────────
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": ["---\n## Step 8: Inspect the Full Conversation History\n\nThis shows exactly what the LLM sees at each step."]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "def run_agent_verbose(user_query: str):\n",
                    "    \"\"\"Same as run_agent but prints the full message history at the end.\"\"\"\n",
                    "    messages = [\n",
                    "        {\"role\": \"system\",  \"content\": \"You are a helpful assistant.\"},\n",
                    "        {\"role\": \"user\",    \"content\": user_query}\n",
                    "    ]\n",
                    "    \n",
                    "    for step in range(10):\n",
                    "        response = simulated_llm(messages)\n",
                    "        \n",
                    "        if response[\"type\"] == \"answer\":\n",
                    "            messages.append({\"role\": \"assistant\", \"content\": response[\"content\"]})\n",
                    "            break\n",
                    "        elif response[\"type\"] == \"tool_call\":\n",
                    "            tool_result = execute_tool(response[\"tool\"], response[\"args\"])\n",
                    "            messages.append({\"role\": \"assistant\", \"content\": None,\n",
                    "                             \"tool_call\": {\"name\": response[\"tool\"], \"args\": response[\"args\"]}})\n",
                    "            messages.append({\"role\": \"tool\", \"content\": tool_result})\n",
                    "    \n",
                    "    print(\"\\n====== FULL CONVERSATION HISTORY ======\")\n",
                    "    for i, msg in enumerate(messages):\n",
                    "        print(f\"\\nMessage {i} | Role: {msg['role'].upper()}\")\n",
                    "        print(\"-\" * 40)\n",
                    "        if \"tool_call\" in msg and msg[\"tool_call\"]:\n",
                    "            print(f\"  Tool Call: {json.dumps(msg['tool_call'], indent=4)}\")\n",
                    "        else:\n",
                    "            print(f\"  Content: {msg.get('content', '')}\")\n",
                    "\n",
                    "run_agent_verbose(\"What is the weather in Tokyo?\")"
                ]
            },

            # ── Step 9: Real API ────────────────────────────
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "---\n",
                    "## Step 9: Use a Real LLM (Groq Free API)\n",
                    "\n",
                    "Groq provides **free API access** to Llama-3 and Mixtral models.\n",
                    "Get your free key at: https://console.groq.com\n",
                    "\n",
                    "> **This cell is optional.** Everything above works without an API key.\n"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# Install Groq client\n",
                    "!pip install -q groq\n",
                    "\n",
                    "import os\n",
                    "from groq import Groq\n",
                    "\n",
                    "# Set your API key\n",
                    "GROQ_API_KEY = \"your_key_here\"  # paste your free key from console.groq.com\n",
                    "\n",
                    "def run_agent_with_real_llm(user_query: str):\n",
                    "    \"\"\"Real agent using Groq (Llama-3) with actual function calling.\"\"\"\n",
                    "    client = Groq(api_key=GROQ_API_KEY)\n",
                    "    \n",
                    "    messages = [\n",
                    "        {\"role\": \"system\", \"content\": \"You are a helpful assistant. Use tools when needed.\"},\n",
                    "        {\"role\": \"user\",   \"content\": user_query}\n",
                    "    ]\n",
                    "    \n",
                    "    # Convert our schemas to Groq format\n",
                    "    groq_tools = [{\"type\": \"function\", \"function\": t} for t in TOOL_SCHEMAS]\n",
                    "    \n",
                    "    print(f\"\\nUSER: {user_query}\")\n",
                    "    \n",
                    "    for step in range(10):\n",
                    "        response = client.chat.completions.create(\n",
                    "            model=\"llama3-8b-8192\",\n",
                    "            messages=messages,\n",
                    "            tools=groq_tools,\n",
                    "            tool_choice=\"auto\",\n",
                    "            temperature=0  # always 0 for tool calling!\n",
                    "        )\n",
                    "        \n",
                    "        msg = response.choices[0].message\n",
                    "        \n",
                    "        # Final answer (no tool call)\n",
                    "        if not msg.tool_calls:\n",
                    "            print(f\"AGENT: {msg.content}\")\n",
                    "            return msg.content\n",
                    "        \n",
                    "        # Process tool calls\n",
                    "        messages.append(msg)  # add assistant message with tool call\n",
                    "        \n",
                    "        for tc in msg.tool_calls:\n",
                    "            tool_name = tc.function.name\n",
                    "            tool_args = json.loads(tc.function.arguments)\n",
                    "            \n",
                    "            print(f\"AGENT calls: {tool_name}({tool_args})\")\n",
                    "            result = execute_tool(tool_name, tool_args)\n",
                    "            print(f\"  Result: {result}\")\n",
                    "            \n",
                    "            messages.append({\n",
                    "                \"role\":         \"tool\",\n",
                    "                \"tool_call_id\": tc.id,\n",
                    "                \"content\":      result\n",
                    "            })\n",
                    "\n",
                    "# Only run if you have a real API key\n",
                    "if GROQ_API_KEY != \"your_key_here\":\n",
                    "    run_agent_with_real_llm(\"What is the weather in Tokyo?\")\n",
                    "else:\n",
                    "    print(\"Paste your Groq API key above to test with a real LLM.\")\n",
                    "    print(\"Get one free at: https://console.groq.com\")"
                ]
            },

            # ── Summary ────────────────────────────────────
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "---\n",
                    "## ✅ Summary: What You Built\n",
                    "\n",
                    "| Component | What it does |\n",
                    "|---|---|\n",
                    "| `get_weather`, `calculate`, `search_web` | The actual Python functions (tools) |\n",
                    "| `TOOL_SCHEMAS` | JSON descriptions the LLM reads to know what tools exist |\n",
                    "| `TOOL_REGISTRY` | Maps tool names → Python functions |\n",
                    "| `execute_tool()` | Safely runs a tool and catches errors |\n",
                    "| `run_agent()` | The full loop: LLM → tool call → execute → feed back → repeat |\n",
                    "\n",
                    "### The Agent Loop in One Picture:\n",
                    "```\n",
                    "User Query\n",
                    "    ↓\n",
                    "LLM decides: tool needed?\n",
                    "    ├── NO  → Final Answer → Done\n",
                    "    └── YES → Tool Call JSON\n",
                    "                  ↓\n",
                    "             execute_tool()\n",
                    "                  ↓\n",
                    "             Append result to messages\n",
                    "                  ↓\n",
                    "             Back to LLM (repeat)\n",
                    "```\n",
                    "\n",
                    "### Next Module: RAG (Retrieval-Augmented Generation)\n",
                    "We will add **long-term memory** to the agent using vector databases."
                ]
            }
        ],
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"}
        },
        "nbformat": 4,
        "nbformat_minor": 2
    }

    with open("module3_tool_calling_colab.ipynb", "w") as f:
        json.dump(notebook, f, indent=2)
    print("✅ Notebook 'module3_tool_calling_colab.ipynb' generated!")

if __name__ == "__main__":
    generate_notebook()
